// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzzNTqwEqVgRtGcWjmwmngXUei0gPfhhQ',
    appId: '1:1063819862062:web:aa6e832c8b182fa13effbf',
    messagingSenderId: '1063819862062',
    projectId: 'nuqta-7267a',
    authDomain: 'nuqta-7267a.firebaseapp.com',
    storageBucket: 'nuqta-7267a.firebasestorage.app',
    measurementId: 'G-ZN7KVFXYDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsA4XmpjB4yZeqnLP3_aI5KSxJUMQFJBI',
    appId: '1:1063819862062:android:8d2cd32b9e73e44e3effbf',
    messagingSenderId: '1063819862062',
    projectId: 'nuqta-7267a',
    storageBucket: 'nuqta-7267a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiqxhKkBxrul0wPWUOB0BDcmxgOk3IUP8',
    appId: '1:1063819862062:ios:8f217e696acd61193effbf',
    messagingSenderId: '1063819862062',
    projectId: 'nuqta-7267a',
    storageBucket: 'nuqta-7267a.firebasestorage.app',
    iosBundleId: 'com.example.nuqta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzzNTqwEqVgRtGcWjmwmngXUei0gPfhhQ',
    appId: '1:1063819862062:web:43628853405571bc3effbf',
    messagingSenderId: '1063819862062',
    projectId: 'nuqta-7267a',
    authDomain: 'nuqta-7267a.firebaseapp.com',
    storageBucket: 'nuqta-7267a.firebasestorage.app',
    measurementId: 'G-2ZXJ2EBM0L',
  );
}
